<x-layouts.dashboard title="Database Query Logs">
    @pushOnce('plugin-styles')
        <link rel="stylesheet" href="{{ asset('vendor/datatables/datatables.min.css') }}" @cspNonce />
    @endPushOnce

    <div class="container-xxl flex-grow-1 container-p-y">
        <div class="d-flex justify-content-between align-items-center mb-4">
            <x-dashboard.breadcrumb />
            @can('log.query.store')
                <button class="btn btn-primary" type="button" id="btn-clear-logs" @disabled($logCount === 0)>
                    Clear Query Logs
                </button>
            @endcan
        </div>

        <p class="mb-4">
            Any server-side logs that are generated by the system will be displayed here.<br/>
            This includes logs for system events, errors, and other important information.<br/>
            You can clear the system logs that more than {{ config('logging.delete_files_older_than_days', 7) }}
            days by clicking the button above.
        </p>

        <div class="card">
            <div class="card-body table-responsive">
                {{ $dataTable->table() }}
            </div>
        </div>
    </div>

    @pushOnce('plugin-scripts')
        <script type="text/javascript" src="{{ asset('vendor/datatables/datatables.min.js') }}" @cspNonce>
        </script>
        <script type="text/javascript" src="{{ asset('vendor/datatables/buttons.server-side.js') }}"
            @cspNonce></script>
    @endPushOnce

    @pushOnce('page-scripts')
        {{ $dataTable->scripts(attributes: ['type' => 'module', 'nonce' => app('csp-nonce')]) }}
        @can('log.query.store')
            <script @cspNonce>
                $(document).on('click', '#btn-clear-logs', function() {
                    const dataTable = $('#query-table').DataTable();
                    if (dataTable.data().count() === 0) return;

                    Swal.fire({
                        title: 'Are you sure?',
                        text: "This action will clear all query logs older than {{ config('logging.delete_files_older_than_days', 7) }} days.",
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'Yes, clear logs!'
                    }).then((result) => {
                        if (result.isConfirmed) {
                            Swal.fire({
                                title: 'Clearing Query Logs...',
                                text: 'Please wait while the query logs are being cleared.',
                                allowOutsideClick: false,
                                allowEscapeKey: false,
                                didOpen: () => {
                                    Swal.showLoading();
                                }
                            });
                            $.ajax({
                                url: '{{ route('dashboard.log.query.store') }}',
                                type: 'POST',
                                data: {
                                    _token: '{{ csrf_token() }}',
                                    log_name: 'query',
                                },
                                success: function(response) {
                                    dataTable.ajax.reload(null, false);

                                    Swal.fire(
                                        'Cleared!',
                                        'Query logs have been cleared.',
                                        'success'
                                    ).then(() => {
                                        if (dataTable.data().count() === 0) {
                                            $('#btn-clear-logs').attr('disabled', true);
                                        } else {
                                            const oldestDate = dataTable.rows().data().reduce((oldest, row) => {
                                                const date = new Date(row.date);
                                                return !oldest || date < oldest ? date : oldest;
                                            }, null);

                                            const thresholdDate = new Date();
                                            thresholdDate.setDate(thresholdDate.getDate() - {{ config('logging.delete_files_older_than_days', 7) }});

                                            if (oldestDate && new Date(oldestDate) > thresholdDate) {
                                                $('#btn-clear-logs').attr('disabled', true);
                                            }
                                        }
                                    });
                                },
                                error: function(xhr) {
                                    Swal.fire(
                                        'Error!',
                                        'Failed to clear query logs. Please try again later.',
                                        'error'
                                    );
                                },
                            });
                        }
                    });
                });
            </script>
        @endcan
    @endPushOnce
</x-layouts.dashboard>
